### ISSUE TITLE
Room Elevations

### ISSUE THREAD

**Issue by ivanzep** [dnenov/pyChilizer#7]
Is there a way that the elevations generated from rooms are individual room markers rather than 1 maker with 4 elevations attached??

**Comment by dnenov** [comment]
Could you describe the scenario in which this would be useful to you? We can certainly have a look on our side.

**Comment by ivanzep** [comment]
Thanks for your reply

I typically keep elevation markers with 1 view on them only because there are cases where not all 4 elevations within a marker end up on the same sheet, which makes the elevation marker not display the sheet number reference. So I find its more flexible to have individual elevation markes.

I also noticed that the your elevation tool does not work with rooms that aren't square or have more than 4 side walls (like a hexagon for example). I tried that to see if it could be a workaround but had no luck.

**Comment by rastermadre** [comment]
Hi [ivanzep](https://github.com/ivanzep), 

It's unlikely that the scenario with non-rectangular rooms will be included in the main Room Data Sheets simply because it's difficult to account for every situation when creating a layout. 

For polygonal non-rectangular rooms we have added an extra button under Room Elevations - **Room Elevations +**
(for now) it only works with sections, and it creates sections aligned to each of the room boundaries.
![image](https://user-images.githubusercontent.com/43077096/154740371-fa42663c-436b-4d86-a47c-d2534c1e0a0c.png)

**Comment by dnenov** [comment]
If you think that didn't 'solve' the usability issue, feel free to raise it again, @ivanzep. I am closing this one down.
